  
name: label on move
on:
  project_card:
    types:
      - moved
      - created
      - converted
jobs:
  label_on_move:
    if: github.event.project_card.column_id == '13116233'
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "bug, help wanted, good-first-issue"
